//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kangaroo.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.RecruitmentSoap")]
    public interface RecruitmentSoap {
        
        // CODEGEN: Generating message contract since element name loginName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Kangaroo.LoginService.LoginResponse Login(Kangaroo.LoginService.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Kangaroo.LoginService.LoginResponse> LoginAsync(Kangaroo.LoginService.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Kangaroo.LoginService.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Kangaroo.LoginService.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kangaroo.LoginService.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Kangaroo.LoginService.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecruitmentSoapChannel : Kangaroo.LoginService.RecruitmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecruitmentSoapClient : System.ServiceModel.ClientBase<Kangaroo.LoginService.RecruitmentSoap>, Kangaroo.LoginService.RecruitmentSoap {
        
        public RecruitmentSoapClient() {
        }
        
        public RecruitmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecruitmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecruitmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecruitmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kangaroo.LoginService.LoginResponse Kangaroo.LoginService.RecruitmentSoap.Login(Kangaroo.LoginService.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string loginName, string password) {
            Kangaroo.LoginService.LoginRequest inValue = new Kangaroo.LoginService.LoginRequest();
            inValue.Body = new Kangaroo.LoginService.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            Kangaroo.LoginService.LoginResponse retVal = ((Kangaroo.LoginService.RecruitmentSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kangaroo.LoginService.LoginResponse> Kangaroo.LoginService.RecruitmentSoap.LoginAsync(Kangaroo.LoginService.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kangaroo.LoginService.LoginResponse> LoginAsync(string loginName, string password) {
            Kangaroo.LoginService.LoginRequest inValue = new Kangaroo.LoginService.LoginRequest();
            inValue.Body = new Kangaroo.LoginService.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((Kangaroo.LoginService.RecruitmentSoap)(this)).LoginAsync(inValue);
        }
    }
}
